#ifndef BTSTACK_CONFIG_H
#define BTSTACK_CONFIG_H

#define ENABLE_BLE 1
#define ENABLE_LE_SECURE_CONNECTIONS 0
#define ENABLE_LE_PERIPHERAL 1

#define HCI_ACL_PAYLOAD_SIZE 80
#define MAX_NR_HCI_CONNECTIONS 1
#define MAX_NR_L2CAP_CHANNELS 2
#define MAX_NR_L2CAP_CREDITS 1
#define MAX_NR_GATT_CLIENTS 1
#define MAX_NR_GATT_SERVICES 4
#define MAX_NR_GATT_CHARACTERISTICS 8
#define MAX_NR_GATT_DESCRIPTORS 4
#define MAX_NR_SM_LOOKUP_ENTRIES 2
#define MAX_NR_WHITELIST_ENTRIES 1
#define MAX_NR_LE_DEVICE_DB_ENTRIES 1
#define NVM_NUM_DEVICE_DB_ENTRIES 1

#define HAVE_EMBEDDED_TIME_MS 1

#define MAX_ATT_DB_SIZE 512

#define ENABLE_LOG_INFO 0
#define ENABLE_LOG_ERROR 1
#define ENABLE_PRINTF_HEXDUMP 1

#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#define HCI_ACL_CHUNK_SIZE_ALIGNMENT 4

#endif
